server:
 port: 5000
 servlet:
    context-path: /mypet
 
spring:
  application:
    name: "mypet"
  datasource:
    url: jdbc:postgresql://localhost:5432/mypet
    username: postgres
    password: postgres
    driver: 
      class: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:/db/dbchangeLog.xml
  jpa:
    hibernate:
      ddl-auto: none
  mail:
      host: smtp.gmail.com
      port: 587
      username: jplazarim@gmail.com
      password: Joaopedroabc.123
      properties:
        mail:
          smtp: 
            auth: true
            starttls:
              enable: true
    